FROM registry.fedoraproject.org/fedora:41

RUN dnf install -y git \
    python3 \
    python3-pip \
    make
RUN pip3 install --upgrade pip

RUN useradd -m -s /usr/bin/bash vscode && \
    echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/vscode

WORKDIR /workspace
